# Generated by Django 4.0.6 on 2022-08-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_file',
            field=models.FileField(upload_to='wallet/'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
