# Generated by Django 4.0.6 on 2022-08-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=15)),
                ('transaction_id', models.IntegerField()),
                ('transaction_amount', models.BigIntegerField()),
                ('customer_id', models.IntegerField()),
                ('status', models.CharField(max_length=6)),
                ('transaction_number', models.CharField(max_length=7)),
                ('date_time', models.DateTimeField()),
                ('transaction_description', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(max_length=15)),
                ('receipt_date', models.DateTimeField()),
                ('bill_number', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('receipt_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Third_Party',
            fields=[
                ('name', models.CharField(max_length=15)),
                ('id', models.CharField(max_length=8)),
                ('type', models.CharField(max_length=6)),
                ('transaction_account', models.IntegerField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wallet.account')),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='signature',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reciept',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_charge',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='datecreated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='type',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='employment_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='proile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile       _pics'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='history',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='pin',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('customer_id', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('points', models.IntegerField()),
                ('date_of_reward', models.DateTimeField()),
                ('recipient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.BigIntegerField()),
                ('loan_type', models.CharField(max_length=15)),
                ('amount', models.BigIntegerField()),
                ('datetime', models.DateTimeField()),
                ('intrest_rate', models.IntegerField()),
                ('payment_due_date', models.DateTimeField()),
                ('loan_balance', models.IntegerField()),
                ('Wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
                ('guaranter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.third_party')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.CharField(max_length=30)),
                ('card_name', models.CharField(max_length=30)),
                ('card_number', models.IntegerField()),
                ('card_type', models.CharField(max_length=30)),
                ('expiry_date', models.DateTimeField()),
                ('card_status', models.CharField(max_length=30)),
                ('security_code', models.IntegerField()),
                ('issuer', models.CharField(max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
    ]
