# Generated by Django 4.1 on 2022-09-01 19:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_receipt_receipt_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=54)),
                ('symbol', models.CharField(max_length=12)),
                ('amount', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.BigIntegerField()),
                ('date_of_issue', models.DateTimeField()),
                ('issuer', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='Wallet',
            new_name='wallet',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='bill_number',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='receipt_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='total_amount',
            new_name='receipt_number',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_charge',
            new_name='transaction_amount',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='customer_id',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_status',
        ),
        migrations.RemoveField(
            model_name='card',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='proile_picture',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='intrest_rate',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='payment_due_date',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reciept',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_time',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='active',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='datecreated',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='time',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='type',
        ),
        migrations.AddField(
            model_name='account',
            name='account_balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='date_of_issue',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile pics'),
        ),
        migrations.AddField(
            model_name='loan',
            name='issuer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reward_transaction', to='wallet.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='message',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_description',
            field=models.CharField(max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Wallet_customer', to='wallet.customer'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account_wallet', to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='issuer',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='guaranter',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_type',
            field=models.CharField(max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Thirdparty_transaction', to='wallet.transaction'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reward_recipient', to='wallet.customer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_destination', to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='origin_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_origin', to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_wallet', to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='history',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Third_Party',
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Thirdparty_account', to='wallet.account'),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Thirdparty_currency', to='wallet.currency'),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Thirdparty_wallet', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Thirdparty_recipient', to='wallet.customer'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Wallet_currency', to='wallet.currency'),
        ),
    ]
