# Generated by Django 4.1 on 2022-09-01 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_card_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdparty',
            name='date_of_issue',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 20, 2, 50, 703106, tzinfo=datetime.timezone.utc)),
        ),
    ]
