# Generated by Django 4.1 on 2022-09-01 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_thirdparty_date_of_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdparty',
            name='date_of_issue',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
