# Generated by Django 4.1 on 2022-09-01 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_reward_date_of_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
